config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'lists#index'

  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "has already been bookmarked in this list" }

end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end


  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to @list
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def edit
    @list = List.find(params[:id])
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit 'Submit', class: 'btn btn-success mt-2' %>
<% end %>

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Add bookmark</h1>
  <%= render 'bookmarks/form', list: @list ,bookmark: @bookmark %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for list do |f| %>
  <%= f.input :photo, as: :file %>
  <%= f.input :name%>
  <%= f.submit 'Submit', class: 'btn btn-success mt-2' %>
<% end %>

app/views/lists/edit.html.erb
<div class="container">
  <h1>Edit List</h1>
  <%= render 'form', list: @list %>
</div>

app/views/lists/index.html.erb
<div class="home-header" style="background-image: url('<%= image_path "wallpaper.png"%>')">
  <div class="container">
    <div class="d-flex py-4">
      <div>
        <%= image_tag "logo.png", style: "height: 150px; width: 150px" %>
      </div>
      <div class="d-flex gap-5 justify-content-center align-items-center col-12 pb-5">
        <div>
          <p class="text-white fs-4"> <%= link_to "Home", root_path, class: "text-white text-decoration-none" %> </p>
        </div>
        <div>
          <p class="fs-4"> <%= link_to "Create a movie list", new_list_path, class: "text-white text-decoration-none" %> </p>
        </div>
      </div>
    </div>
    <div>
      <div class="py-5">
        <h1 class="">YOUR HOME FOR <br>
          MOVIE
        </h1>
        <h1>
          <div class="animation">BOOKMARKING</div>
        </h1>
      </div>
    </div>
  </div>
</div>
<div class="home-body py-5 d-flex">
  <div class="d-flex flex-wrap">
    <% @lists.each do |list| %>
      <div class="row md-3">
        <div class="d-flex justify-content-center align-items-center col-md-6">
          <%= link_to list.name, list_path(list), class: "text-black text-decoration-none" %>
        </div>
        <div class="d-flex flex-wrap col-md-6">
          <% list.bookmarks.each do |bookmark| %>
            <img src="<%= bookmark.movie.poster_url%>" alt="" style="height: 270px">
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Add List</h1>
  <%= render 'lists/form', list: @list %>
</div>

app/views/lists/show.html.erb
<div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : image_path('showlogo.png') %>)">
    <p><%= @list.name %></p>
  </div>
  <p class="btn btn-success m-3">
    <%= link_to "add a movie", new_list_bookmark_path(@list) %>
  </p>
  <p class="btn btn-success m-3">
    <%= link_to "Edit", edit_list_path %>
  </p>
  <p>
    <%= link_to "Delete Lesson",
                list_path(@list),
                class: "btn btn-danger",
                data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this Bookmark?" }
                 %>
  </p>
  <div class="d-flex justify-content-center">
    <div class="cards">
      <% @bookmarks.each do |bookmark| %>
        <div class="card-trip">
          <img src=<%= bookmark.movie.poster_url %>/>
          <div >
            <div>
              <h2><%= bookmark.movie.title %></h2>
              <p><%= bookmark.movie.overview %></p>
              <p><b>"</b><%= bookmark.comment %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>